version: "3.8"
services:
  springboot-app:
    image: springboot-app
    restart: always
    build: .
    ports: 
       - 9090:8080
    environment:
      MYSQL_HOST: newmysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: varun
      MYSQL_PORT: 3306

       
  mysqldb:
   container_name: newmysqldb
   image: mysql
   ports:
    - 3308:3306
   environment:
     MYSQL_DATABASE: test
     MYSQL_ROOT_PASSWORD: varun 